# This is a basic workflow to help you get started with Actions

name: PUSHING_PELOSI

# Controls when the workflow will run
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
          
      - run: pip install -r ./PUSHING_PELOSI/requirements.txt

      - name: Run PUSHING_PELOSI
        env:
          api_key: ${{ secrets.API_KEY }}
          api_secret: ${{ secrets.API_SECRET }}
          csrf_token: ${{ secrets.CSRFTOKEN }}
          qq_api_token: ${{ secrets.QQAPITOKEN }}
        run: python main.py
